### ISSUE TITLE
Issue while building apk 

### ISSUE THREAD

**Issue by varaprasadreddy9676** [Zeno97/cordova-plugin-jitsi-meet-sdk#1]
Getting this error while building apk in ionic.
Any Idea why I'm getting this.

BUILD FAILED in 1m 5s
C:\Users\MSVReddy\Documents\medics-development\medics-care\medics-care_newJitsi\medics-care-app\platforms\android\gradlew: Command failed with exit code 1 Error output:
C:\Users\MSVReddy\Documents\medics-development\medics-care\medics-care_newJitsi\medics-care-app\platforms\android\app\src\main\java\org\jitsi\meet\JitsiMeet\JitsiMeet.java:140: error: cannot find symbol
        JitsiMeetActivity jitsiMeetActivity = JitsiMeetActivity.getInstance();
                                                               ^
  symbol:   method getInstance()
  location: class JitsiMeetActivity
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\Users\MSVReddy\Documents\medics-development\medics-care\medics-care_newJitsi\medics-care-app\platforms\android\app\src\main\java\org\apache\cordova\file\AssetFilesystem.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 5s

**Comment by Zeno97** [comment]
For anyone is having this trouble until I solve use ANDROID STUDIO to build apk.
As discussed in #4 it happens only with cordova CLI commands.
Thanks

**Comment by Zeno97** [comment]
Hi @ManivannanVC i've implemented newer jitsi meet sdk, fixed this problem and also implemented participant related listeners.
You can find every new implementation in the doc.
