### ISSUE TITLE
Failed to install 'cordova-plugin-jitsi-meet-sdk': TypeError: Cannot convert undefined or null to object 

### ISSUE THREAD

**Issue by youssmak** [Zeno97/cordova-plugin-jitsi-meet-sdk#14]
when trying to install plugin for iOS using `cordova plugin add cordova-plugin-jitsi-meet-sdk --save`
i'm using cordova-cli@10.0.0

**Comment by Zeno97** [comment]
I am using version 6. Use the last one of cordova 10.
I create source code with cordova cli and build with xcode

**Comment by youssmak** [comment]
@Zeno97 thks, it works !
but not with cordova-ios@5.1.1
