### ISSUE TITLE
don't see camera in of the other person

### ISSUE THREAD

**Issue by gitsistematico** [Zeno97/cordova-plugin-jitsi-meet-sdk#22]
help me please, when i into de videocall i can not see the camera of other user in the app

![image](https://user-images.githubusercontent.com/32254399/183736559-419d8ea5-ef39-4405-b4b2-fc28893140fc.png)

**Comment by Zeno97** [comment]
Hello.
Probably you should check if the app has permissions to access camera for both devices.
For some android device there are additional permissions that usually blocks features if not accepted like in your case. For this reason you should also test with different devices.



Inviato dal mio Galaxy



-------- Messaggio originale --------
Da: gitsistematico ***@***.***>
Data: 09/08/22 20:45 (GMT+01:00)
A: Zeno97/cordova-plugin-jitsi-meet-sdk ***@***.***>
Cc: Subscribed ***@***.***>
Oggetto: [Zeno97/cordova-plugin-jitsi-meet-sdk] don't see camera in of the other person (Issue #22)


help me please, when i into de videocall i can not see the camera of other user in the app

[image]<https://user-images.githubusercontent.com/32254399/183736559-419d8ea5-ef39-4405-b4b2-fc28893140fc.png>

**Comment by Zeno97** [comment]
Hello? Do you solved?

**Comment by dopplerDistortion** [comment]
Encountered same issue today. Trying to understand whats wrong. Dropping scenarios that I encounter

First scenario with cordova plugin
- Created a room at meet.jitsi with one computer
- Joined same room from another computer
- Joined same room with app that have cordova-plugin-jitsi-meet-sdk plugin 
- Two other computer seems audio muted & video muted in the app BUT we can hear audio transmission. App cannot see two other computers.

Second senario with jitsi app google play
- Created a room at meet.jitsi with one computer
- Joined same room from another computer
- Joined same room with Jitsi Meet App
- Two other computer's audio is OK & video is OK

**Comment by gitsistematico** [comment]
we resolved this problem when updated service with jitsi meet at the last version with the 8x8 provider.

https://jaas.8x8.vc/#/

the problem was in the token configurations to access the room.

**Comment by gitsistematico** [comment]
Hello Massimiliano,  yes  this solved my problem, thank's
