### ISSUE TITLE
no visible @interface for 'JitsiMeetConferenceOptionsBuilder'  when i compile

### ISSUE THREAD

**Issue by ricardorinconremolina** [Zeno97/cordova-plugin-jitsi-meet-sdk#24]
HI  Zeno97, I have a problem when I compile ti IOS.
Plis can you help me, 
You know,  How can I resolve it ?
![Captura de Pantalla 2022-08-19 a la(s) 3 05 11 p m](https://user-images.githubusercontent.com/111593781/185698968-ef397887-152f-4c8c-a16f-a36a014e2dd3.png)

**Comment by Zeno97** [comment]
cordova platform remove ios
cordova platform add ios

Open with xCode the ios folder generated and try to build with it



Inviato dal mio Galaxy



-------- Messaggio originale --------
Da: ricardorinconremolina ***@***.***>
Data: 19/08/22 22:09 (GMT+01:00)
A: Zeno97/cordova-plugin-jitsi-meet-sdk ***@***.***>
Cc: Subscribed ***@***.***>
Oggetto: [Zeno97/cordova-plugin-jitsi-meet-sdk] no visible @interface for 'JitsiMeetConferenceOptionsBuilder' when i compile (Issue #24)


HI Zeno97, I have a problem when I compile ti IOS.
Plis can you help me,
You know, How can I resolve it ?
[Captura de Pantalla 2022-08-19 a la(s) 3 05 11 p m]<https://user-images.githubusercontent.com/111593781/185698968-ef397887-152f-4c8c-a16f-a36a014e2dd3.png>

**Comment by ricardorinconremolina** [comment]
HI zeno 97, then I tried and don't working, i have the same  error.
![Captura de Pantalla 2022-08-22 a la(s) 8 50 37 a m](https://user-images.githubusercontent.com/111593781/186011406-7a9e0508-bd11-4590-aa7e-3a233e13713e.png)

**Comment by Zeno97** [comment]
Hello i have fixed the jitsi meet sdk version to 3.10.4.
Probably had been major realeses that deprecated some code.

Try remove and install this plugin, remove and add platform ios and let me know

**Comment by ricardorinconremolina** [comment]
hello Zeno97,  
i have a question,

what is the install ? : 
1- npm i cordova-plugin-jitsi-meet-sdk@4.0.4
or
2-  cordova plugin add cordova-plugin-jitsi-meet-sdk

**Comment by Zeno97** [comment]
cordova plugin add cordova-plugin-jitsi-meet-sdk


Inviato dal mio Galaxy



-------- Messaggio originale --------
Da: ricardorinconremolina ***@***.***>
Data: 25/08/22 16:32 (GMT+01:00)
A: Zeno97/cordova-plugin-jitsi-meet-sdk ***@***.***>
Cc: Massimiliano Coppola ***@***.***>, Comment ***@***.***>
Oggetto: Re: [Zeno97/cordova-plugin-jitsi-meet-sdk] no visible @interface for 'JitsiMeetConferenceOptionsBuilder' when i compile (Issue #24)


hello Zeno97,
i have a question,

what is the install ? :
1- npm i ***@***.***
or
2- cordova plugin add cordova-plugin-jitsi-meet-sdk

**Comment by ricardorinconremolina** [comment]
hello Zeno97,
I tried your indication and compiled on Xcode and now  I have this Error:

![Captura de Pantalla 2022-08-25 a la(s) 2 32 25 p m](https://user-images.githubusercontent.com/111593781/186753274-79781860-4e9b-4e71-b038-5883c3f4cc08.png)

thank's you for help me

**Comment by Zeno97** [comment]
You need to select 'compile for all arm64 devices' instead of ipod or directly to real device



Inviato dal mio Galaxy



-------- Messaggio originale --------
Da: ricardorinconremolina ***@***.***>
Data: 25/08/22 21:39 (GMT+01:00)
A: Zeno97/cordova-plugin-jitsi-meet-sdk ***@***.***>
Cc: Massimiliano Coppola ***@***.***>, Comment ***@***.***>
Oggetto: Re: [Zeno97/cordova-plugin-jitsi-meet-sdk] no visible @interface for 'JitsiMeetConferenceOptionsBuilder' when i compile (Issue #24)


hello Zeno97,
I tried your indication and compiled on Xcode and now I have this Error:

[Captura de Pantalla 2022-08-25 a la(s) 2 32 25 p m]<https://user-images.githubusercontent.com/111593781/186753274-79781860-4e9b-4e71-b038-5883c3f4cc08.png>

thank's you for help me

**Comment by ricardorinconremolina** [comment]
thak's zeno97,
this fixes is working, so thak's,
the better solution is compile on device
