### ISSUE TITLE
no visible @interface for 'JitsiMeetConferenceOptionsBuilder' declares the selector 'setWelcomePageEnabled:'

### ISSUE THREAD

**Issue by ricardorinconremolina** [Zeno97/cordova-plugin-jitsi-meet-sdk#25]
HI zeno 97, then I tried and don't working, i have the same error.

It would be possible to contact us to compile in ios, I am willing to pay for your advice
could you confirm me please ?.

![Captura de Pantalla 2022-08-22 a la(s) 8 50 37 a m](https://user-images.githubusercontent.com/111593781/186485027-7c9b8aea-1a2e-41ad-8e26-2a0ec38a8c23.png)

**Comment by ricardorinconremolina** [comment]
what's your last cordova version for ios  and xcode ?

**Comment by Zeno97** [comment]
Solved in https://github.com/Zeno97/cordova-plugin-jitsi-meet-sdk/issues/24
