### ISSUE TITLE
typo / mistake in example code

### ISSUE THREAD

**Issue by viking2917** [Zeno97/cordova-plugin-jitsi-meet-sdk#29]
in the example code in the Readme, the parameter

```
"video-share.enabled": true,
```

is included twice, which some code linters will complain about.

**Comment by Zeno97** [comment]
Thank you
Fixed here
https://github.com/Zeno97/cordova-plugin-jitsi-meet-sdk/commit/adb5fedd25526b37a5cf263dc4cc6334b8f8b0f6
