### ISSUE TITLE
Listeners are not fired

### ISSUE THREAD

**Issue by ManivannanVC** [Zeno97/cordova-plugin-jitsi-meet-sdk#4]
Hi,

Thanks for the wonderful effort on it.

I installed your plugin and fixed issue on platforms\android\app\src\main\java\org\jitsi\meet\JitsiMeet\JitsiMeet.java by changing the below line
FROM 
**JitsiMeetActivity jitsiMeetActivity = JitsiMeetActivity.getInstance();**
To
**JitsiMeetActivity jma = new JitsiMeetActivity();**

I got successful build and connected to meeting successfully.

Now the problem is listeners are not getting fired. Please help me on this!. Thanks in advance.

**Comment by Zeno97** [comment]
Hello.
Normally you were not supposed to change any lines in the java code.
Please explain what issue do you had before.

**Comment by ManivannanVC** [comment]
Hi Zeno97,

Thanks for the quick reply. I changed the code because of i am getting the same error reported already in this URL https://github.com/Zeno97/cordova-plugin-jitsi-meet-sdk/issues/1. So i have changed the line as i mentioned earlier.

When i am trying to get console log of listeners it was not getting fired. 

My Code Is,

var meetingOptions={
serverURL: "https://"+meetingURL,
room: params.sessionid,
displayName: (params.userFullName).trim(),
email: "moderator",
audioMuted: true,
videoMuted: true,
welcomePageEnabled: false,
subject: params.meeting_title,
audioOnly: (params.participantVideo=='1'?false:true),
/*token: params.token,*/
flags: {
				"chat.enabled": true,
				"invite.enabled": false,
				"kick-out.enabled": false,
				"live-streaming.enabled": true,
				"pip.enabled": true,
				"raise-hand.enabled":false,
				"recording.enabled": true,
				"video-share.enabled": true,
				"add-people.enabled": true,
				"conference-timer.enabled": true,
				"meeting-name.enabled": true,
				"video-share.enabled": true,
				"meeting-password.enabled": false,
				"toolbox.alwaysVisible": true
}
};
function jitsiListener(listener){
	console.log(listener);
    alert(listener);
    switch(listener){
        case "onConferenceWillJoin":
            //you are going to join into conference
            
            break;
        case "onConferenceJoined":
            //you are full entered into conference
            break;
        case "onConferenceTerminated":
            //you left the conference
            mainView.router.load({url:'./index.html'});
			upComingMeeting();
			totalMeetings();
        break;
        case "onCreate":
            //JitsiMeetActivity is created
            break;
        case "onDestroy":
            //JitsiMeetActivity is destroyed
            break;
        case "onBackPressed":
            //has been pressed backbutton inside JitsiMeetActivity
            break;
        case "onNewIntent":
            //JitsiMeetActivity has fired onNewIntent event
            break;
        case "onUserLeaveHint":
            //JitsiMeetActivity is in Picture in Picture mode
            break;
    }
}
JitsiMeet.startConference(meetingOptions, jitsiListener);

Did i make any mistake ?

**Comment by Zeno97** [comment]
To make listeners work you have use my original code
To not get stuck in bug #1 you need to compile apk with android sudio build option and not with cli commands like cordova build or cordova run.

**Comment by ManivannanVC** [comment]
Thanks Zeno97. It is working fine with android studio version.
