### ISSUE TITLE
How to call participant events?

### ISSUE THREAD

**Issue by ManivannanVC** [Zeno97/cordova-plugin-jitsi-meet-sdk#5]
Hi Zeno97,

I am not able to get this events like **PARTICIPANT_JOINED,PARTICIPANT_LEFT and ENDPOINT_TEXT_MESSAGE_RECEIVED**. How to get this listeners ?

**Comment by Zeno97** [comment]
Hello.
Actually those events are not supported because there are no methods in the android sdk which this plugin is based for 
Look at here: https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-android-sdk

**Comment by Zeno97** [comment]
As a workaround i suggest you to implement this from scratch with websocket

**Comment by Zeno97** [comment]
Hi @ManivannanVC i've implemented newer jitsi meet sdk and also implemented participant related listeners.
You can find every new implementation in the doc.
