### ISSUE TITLE
Signed APK gives an Error

### ISSUE THREAD

**Issue by ManivannanVC** [Zeno97/cordova-plugin-jitsi-meet-sdk#7]
Hi Zeno97,

As stated in issue #4 , the debug version is working fine. When i make with signed release version , it gives an error like below,

Program type already present: org.jitsi.meet.sdk.AudioDeviceHandlerConnectionService$1

Please help me to resolve this!

**Comment by Zeno97** [comment]
Hello try to build witu android studio and let me know



Inviato dal mio Galaxy



-------- Messaggio originale --------
Da: ManivannanVC ***@***.***>
Data: 29/06/21 14:38 (GMT+01:00)
A: Zeno97/cordova-plugin-jitsi-meet-sdk ***@***.***>
Cc: Subscribed ***@***.***>
Oggetto: [Zeno97/cordova-plugin-jitsi-meet-sdk] Signed APK gives an Error (#7)


Hi Zeno97,

As stated in issue #4<https://github.com/Zeno97/cordova-plugin-jitsi-meet-sdk/issues/4> , the debug version is working fine. When i make with signed release version , it gives an error like below,

/var/www/html/mounts/mac/android/ssv_pammal/platforms/android/app/build/outputs/apk/debug/app-debug.apk

Please help me to resolve this!

**Comment by ManivannanVC** [comment]
![image](https://user-images.githubusercontent.com/64186674/123803006-82f59e00-d909-11eb-992e-9b74e5c9a7e6.png)


Please check the attached image

**Comment by Zeno97** [comment]
Do you have installed multidex plugin?



Inviato dal mio Galaxy



-------- Messaggio originale --------
Da: ManivannanVC ***@***.***>
Data: 29/06/21 15:11 (GMT+01:00)
A: Zeno97/cordova-plugin-jitsi-meet-sdk ***@***.***>
Cc: Zeno97 ***@***.***>, Comment ***@***.***>
Oggetto: Re: [Zeno97/cordova-plugin-jitsi-meet-sdk] Signed APK gives an Error (#7)


[image]<https://user-images.githubusercontent.com/64186674/123803006-82f59e00-d909-11eb-992e-9b74e5c9a7e6.png>

Please check the attached image

**Comment by ManivannanVC** [comment]
no

**Comment by ManivannanVC** [comment]
Do i need to install it ?

**Comment by ManivannanVC** [comment]
Same issue after install multidex plugin!

**Comment by ManivannanVC** [comment]
Any update on this?

**Comment by Zeno97** [comment]
Hi sorry for the issue i will solve it as soon as possible.



Inviato dal mio Galaxy



-------- Messaggio originale --------
Da: ManivannanVC ***@***.***>
Data: 29/06/21 15:11 (GMT+01:00)
A: Zeno97/cordova-plugin-jitsi-meet-sdk ***@***.***>
Cc: Zeno97 ***@***.***>, Comment ***@***.***>
Oggetto: Re: [Zeno97/cordova-plugin-jitsi-meet-sdk] Signed APK gives an Error (#7)


[image]<https://user-images.githubusercontent.com/64186674/123803006-82f59e00-d909-11eb-992e-9b74e5c9a7e6.png>

Please check the attached image

**Comment by ManivannanVC** [comment]
Thanks. Any quick work around for this ?

**Comment by ManivannanVC** [comment]
What are all the dependencies needs to be exclude from https://github.com/jitsi/jitsi-maven-repository/raw/master/releases ?

**Comment by ManivannanVC** [comment]
There is a conflict of package when you pull from https://github.com/jitsi/jitsi-maven-repository/raw/master/releases and sdk loaded in a local directory [sdks/android/sdk](https://github.com/Zeno97/cordova-plugin-jitsi-meet-sdk/tree/main/sdks/android/sdk).

How can we resolve this issue?

**Comment by Zeno97** [comment]
The package included in the plugin is not supposed to be directly updated from repository because has been modified for the scope to work. If you want to solve this issue yourself with the last version of the sdk you should create the plugin from scratch.
You can take mine as a reference.


Inviato dal mio Galaxy



-------- Messaggio originale --------
Da: ManivannanVC ***@***.***>
Data: 30/06/21 10:08 (GMT+01:00)
A: Zeno97/cordova-plugin-jitsi-meet-sdk ***@***.***>
Cc: Zeno97 ***@***.***>, Comment ***@***.***>
Oggetto: Re: [Zeno97/cordova-plugin-jitsi-meet-sdk] Signed APK gives an Error (#7)


There is a conflict of package when you pull from https://github.com/jitsi/jitsi-maven-repository/raw/master/releases and sdk loaded in a local directory sdks/android/sdk<https://github.com/Zeno97/cordova-plugin-jitsi-meet-sdk/tree/main/sdks/android/sdk>.

How can we resolve this issue?

**Comment by ManivannanVC** [comment]
Hi zeno,

Which react native version have you used in your deployment?

https://github.com/jitsi/jitsi-maven-repository/tree/master/releases/com/facebook/react/react-native

**Comment by Zeno97** [comment]
Hi @ManivannanVC i've implemented newer jitsi meet sdk, fixed this problem and also implemented participant related listeners.
You can find every new implementation in the doc.
